name: "Task issue"
description: "Taskレベルのissueをつくる"
title: "【対象ドメイン】Task内容"
labels: ["🍎 task"]
projects: ["tdrk-inc/6"]
body:
  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: ニーズを書く。課題感、重要性を共有するために書く。

  - type: textarea
    id: user-story
    attributes:
      label: ユーザーストーリー
      description: |
        この機能を利用したユーザーが、どのようなメリットを享受するか
        また、エンドユーザー以外の登場人物もすべて網羅する
        ※CS やコンテンツ運用者、分析者等

  - type: dropdown
    id: device
    attributes:
      label: デバイス
      description: PC か、スマホか、はたまたアプリか
      options:
        - PC
        - スマホ
        - PC・スマホ両方
        - アプリ
        - その他
  - type: textarea
    id: scope
    attributes:
      label: 影響範囲
      description: サービス側か、管理画面かなど。URLも書く。

  - type: textarea
    id: kpi
    attributes:
      label: KPI
      description: |
        できるだけ定量的に書く
        定量化が難しければ定性的に書く。

  - type: input
    id: release-date
    attributes:
      label: リリース希望日
      description: 希望なのか、デッドラインなのか、理由も含めて明記

  - type: textarea
    id: risks
    attributes:
      label: リスク
      description: |
        認識しているリスクがあれば記載、かつ対処法も記載
        ※リスクはいくらでもあるので「このリスクは許容する」という合意を得るために記載

  - type: textarea
    id: stakeholders
    attributes:
      label: ステークホルダ
      description: |
        要件に対してレビュー/承認してもらう人を明記
        開発的なレビューと、それ以外のレビューがあるため、全員を記載する。

  - type: textarea
    id: references
    attributes:
      label: 参照
      description: 参考資料，他社事例を書く

  - type: markdown
    attributes:
      value: |
        ---
        ## 〜ここからは開発者がコメントに書く〜

  - type: textarea
    id: estimation
    attributes:
      label: 工数見積もり
      description: 開発者が記入する工数見積もり

  - type: input
    id: planned-release
    attributes:
      label: リリース予定日
      description: 開発者が記入するリリース予定日

  - type: textarea
    id: specifications
    attributes:
      label: 仕様
      description: 開発者が記入する詳細仕様

  - type: textarea
    id: tasks
    attributes:
      label: タスク
      description: 細かいタスクに分解できているなら書き出す
      value: "- [ ] "
